config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :trips, only: [:index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [:create, :update]
    resources :reviews, only: [:new, :create]
  end
  namespace :user do
    resources :trips, only: :index
  end
  resources :bookings, only: :destroy
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :driver, class_name: "User"
  has_many :bookings
  validates :start_point, presence: :true
  validates :end_point, presence: :true
  validates :start_time, presence: :true
  validates :seats_available, presence: :true, numericality: { only_integer: true, greater_than: 0 }
  has_many :users, through: :bookings, source: :passenger, foreign_key: :passenger_id
  has_many :reviews

  def start_date
    start_time.to_date
  end

  def end_date
    end_time.to_date
  end

  def seats_remain
    booked_seats = 0
    bookings.each do |booking|
      booked_seats += booking.seats_number.to_i if booking.approved?
    end
    return seats_available - booked_seats
  end

  # after_validation :geocode, if: :will_save_change_to_start_point?

  geocoded_by :end_point, latitude: :end_lat, longitude: :end_lng
  geocoded_by :start_point, latitude: :start_lat, longitude: :start_lng
  after_validation :geocode_endpoints

  def booking?(user)
    bookings.each do |booking|
      return true if booking.passenger == user
    end
    return false
  end

  def driver?(user)
    driver == user
  end

  def approved_passenger?(user)
    bookings.each do |booking|
      return true if booking?(user) && booking.approved
    end
    return false
  end

  def users_other_than_(user)
    if user == driver
      users
    else
      users.where.not(id: user).to_a << driver
    end
  end

  private

  def geocode_endpoints
    if end_point_changed?
      geocoded = Geocoder.search(end_point).first
      if geocoded
        self.end_lat = geocoded.latitude
        self.end_lng = geocoded.longitude
      end
    end
    if start_point_changed?
      geocoded = Geocoder.search(start_point).first
      if geocoded
        self.start_lat = geocoded.latitude
        self.start_lng = geocoded.longitude
      end
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show]
  skip_before_action :authenticate_user!, only: :index

  def index
    @trips = policy_scope(Trip).where('start_time >= ?', DateTime.now)
    filter_by_date(params[:date])
    filter_by_journey(origin: params[:from], destination: params[:to])

    if params[:from].present?
      @markers = @trips.map do |trip|
        {
          lat: trip.start_lat,
          lng: trip.start_lng,
          infoWindow: render_to_string(partial: "trips/infowindow", locals: { trip: trip }),
          image_url: helpers.asset_url('/app/assets/images/logo.jpeg')
        }
      end
    elsif params[:to].present?
      @markers = @trips.map do |trip|
        {
          lat: trip.end_lat,
          lng: trip.end_lng,
          infoWindow: render_to_string(partial: "trips/infowindow", locals: { trip: trip }),
          image_url: helpers.asset_url('/app/assets/images/logo.jpeg')
        }
      end
    end
  end

  def show
    @booking = Booking.new
    @booking.trip = @trip
  end

  def new
    @trip = Trip.new
    authorize @trip
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.driver = current_user
    authorize @trip
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  private

  def filter_by_date(date = '')
    if date.present?
      date_time = DateTime.parse(date)
      @trips = @trips.where('start_time >= ? AND start_time < ?', date_time, date_time + 3)
    end
  end

  def filter_by_journey(destination: '', origin: '')
    if origin.present? && destination.present?
      # @trips = @trips.near(destination, 30, latitude: :end_lat, longitude: :end_lng).near(origin, 30, latitude: :start_lat, longitude: :start_lng)
      @trips = @trips.near(destination, 30, latitude: :end_lat, longitude: :end_lng) & @trips.near(origin, 30, latitude: :start_lat, longitude: :start_lng)
    elsif origin.present? || destination.present?
      @trips = @trips.near(destination, 30, latitude: :end_lat, longitude: :end_lng) + @trips.near(origin, 30, latitude: :start_lat, longitude: :start_lng)
    end
  end

  def trip_params
    params.require(:trip).permit(:description, :seats_available, :start_point, :end_point, :start_time, :end_time, :price)
  end

  def set_trip
    @trip = Trip.find(params[:id])
    @bookings = Booking.where(trip_id: params[:id])
    authorize @trip
  end
end

app/controllers/user/trips_controller.rb
class User::TripsController < ApplicationController
  def index
    # @trips = TripPolicy::User.new(current_user, User).resolve
    @trips = policy_scope(Trip, policy_scope_class: TripPolicy::User)
    @upcoming_trips = @trips.where("start_time >= '#{DateTime.now}'")
    @past_trips = @trips.where("start_time < '#{DateTime.now}'")
  end

#   def rating
#     @passenger_rating = 0
#     @driver_rating = 0
#   end
end

app/views/trips/_booking_confirmation.html.erb
<div>
  <h2> <%= @trip.description %></h2>
  <div class="card-journey d-flex flex-wrap">
        <h3 class="card-journey-origin mr-3"><p class="m-0"><small><%= @trip.start_time.strftime("%H:%M") %></small></p><%= @trip.start_point %></h3>
        <div class="d-flex align-items-center">
          <i class="fas fa-arrow-circle-right mr-3"></i>
          <h3 class="card-journey-destination"><p class="m-0"><small><%= @trip.end_time.strftime("%H:%M") %></small></p><%= @trip.end_point %></h3>
        </div>
  </div>
  <div class="d-flex justify-content-center">
  <%= simple_form_for [@trip, @booking] do |f| %>
    <%= f.input :number_seats%>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
  </div>
</div>

app/views/trips/_card.html.erb
<div class="card-trip border<% if trip.driver?(current_user) %> driver-tab<% elsif trip.approved_passenger?(current_user) %> booking-approved
    <% elsif trip.approved_passenger?(current_user).nil? %> booking-pending
    <% end %>
">
  <div class="row d-flex justify-content-between m-0 py-3 px-4 h-100">
    <div class="card-left d-flex flex-column col-9 justify-content-between">
      <small class="m-0"><%#= trip.start_time.strftime("%d/%m/%Y") %></small>
      <div class="card-journey d-flex flex-wrap-0">
        <div class="card-journey-origin mr-3"><p class="m-0"><%= trip.start_time.strftime("%H:%M") %></p><h3><%= trip.start_point %></h3></div>
        <div class="d-flex align-items-center">
          <i class="fas fa-arrow-circle-right mr-3"></i>
          <div class="card-journey-destination"><p class="m-0"><%= trip.end_time.strftime("%H:%M") %></p><h3><%= trip.end_point %></h3></div>
        </div>
      </div>
      <div class="card-tags">
        <i class="fas fa-venus-double"></i><i class="fas fa-smoking-ban"></i>
      </div>
    </div>
    <div class="card-right d-flex flex-wrap-0 flex-column justify-content-between text-right">
      <div class="card-driver">
        <% if current_user == trip.driver %>
          <i class="fas fa-car fa-2x driver-icon"></i>
        <% else %>
          <%#= trip.driver.username %>
          <%= cl_image_tag trip.driver.photo, gravity: "faces", crop: "fill", class: "avatar" %>
        <% end %>
      </div>
      <% review = Review.new(trip: trip) %>
      <%# if policy(review).create? %>
        <!-- <div> <%#= link_to "Review", new_trip_review_path(trip) %></div> -->
      <%# end %>
      <h4 class="card-price m-0">
        ¥<%= trip.price %>
      </h4>
    </div>
  </div>
</div>

app/views/trips/_card_bookings_driver.html.erb
<div class="d-flex justify-content-around align-items-center">
  <div class="card-user d-flex align-items-center bg-white my-3 my-md-3 py-3 justify-content-between">
    <div class="user-details d-flex align-items-center">
      <%= cl_image_tag booking.passenger.photo, gravity: "faces", crop: "fill", class: "avatar-large mr-3" %>
      <div class="mr-5 ml-3">
        <div class="row p-0 mt-0 mb-0">
          <p class=""><%= booking.passenger.username %></p>
        </div>
        <div class="row p-0 mt-0 mb-0">
          <%= render "shared/stars", user: booking.passenger%>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex align-items-center bg-white my-3 my-md-3 py-3 justify-content-between ml-5">

      <div>
        <% if booking.approved == true %>
          <button type="button" class="btn btn-outline-primary px-5" disabled>Approved!</button>

        <% else %>
        <%= simple_form_for [booking.trip, booking] do |f| %>
          <%= f.input :approved, as: :hidden, input_html: { value: :true } %>
          <%#= f.submit class: 'btn btn-primary' do %>
          <%= f.submit "Approve", class: "btn btn-primary px-5 w-100", style: "margin-top: -19px" do %>
            <i class="fas fa-thumbs-up"></i></i> Approve <%= booking.passenger.username %>'s request ?
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="ml-3">
        <%= simple_form_for [booking.trip, booking] do |f| %>
        <%= f.input :approved, as: :hidden, input_html: { value: :false } %>
        <%#= f.submit class: 'btn btn-primary' do %>
        <%= f.submit "  Deny  ", class: "btn btn-danger px-5 w-100", style: "margin-top: -19px" do %>
          <i class="fas fa-thumbs-up"></i></i> Reject <%= booking.passenger.username %>'s request ?
          <% end %>
        <% end %>
      </div>

  </div>
</div>

app/views/trips/_card_journey_summary.html.erb
<div class="journey-summary shadow col-12">
  <h2 class="text-center"><%= trip.start_time.strftime("%a, %e %b %Y") %></h2>
    <div class="d-flex justify-content-around mb-3 flex-wrap">
        <div class="card-journey-origin col-12 col-lg-5">
          <small>Departure:</small>
          <p><%= trip.start_time.strftime("%H:%M") %></p>
          <h3> <%= trip.start_point %>  </h3>
        </div>
        <i class="fas fa-2x fa-arrow-circle-right my-3 col-12 col-lg-2"></i>
        <div class="card-journey-destination col-12 col-lg-5">
          <small>Arrival (est.):</small>
          <p><%= trip.end_time.strftime("%H:%M") %></p>
          <h3> <%= trip.end_point %> </h3>
        </div>
    </div>
</div>

app/views/trips/_cards.html.erb
<div class="cards-container">
  <% trips_by_date = trips.group_by { |trip| trip.start_date } %>
  <% trips_by_date.keys.sort.each do |date| %>
    <p class="departure-date text-center"><%= Date.today < date ? 'Departing on' : 'Completed on'%> <strong><%= date%></strong></p>
    <% trips_by_date[date].each do |trip| %>
      <%= link_to trip_path(trip) do %>
        <%= render partial: "trips/card", locals: { trip: trip } %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/trips/_details.html.erb
<h3>Details</h3>
<p><%= trip.description %></p>

<%= render "trips/tags/female_only" %>
<%= render "trips/tags/no_smoking" %>

<%= render partial: "user/card", locals: { user: trip.driver } %>

app/views/trips/_form.html.erb
<%= simple_form_for(booking) do |f| %>
  <div class="form-inputs">
  <% f.input :approved, as: :hidden, :input_html => {value: true} %>
  <%= f.input_field :seats_number %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trips/_form_search.html.erb
<form id="trips-search" data-controller="places" method="get" action="/trips" class="simple_form search col-12 col-lg-8 mx-auto">
  <div class="form-row">
    <div class="col-sm-6 col-lg-4 mb-3 px-0">
      <label for="from">From</label>
      <input type="text" id="from" name="from" class="form-control" placeholder="Leaving from" value="<%= params[:from] %>" data-target="places.inputAddress">
    </div>
    <div class="col-sm-6 col-lg-4 mb-3 px-0">
      <label for="to">To</label>
      <input type="text" id="to" name="to" class="form-control" placeholder="Going to" value="<%= params[:to] %>" data-target="places.inputAddress">
    </div>
    <div class="col-lg-4 mb-3 px-0">
      <label for="date">When</label>
      <input type="date" id="date" name="date" class="form-control" value="<%= params[:date] %>" optional>
    </div>
  </div>
  <div class="form-row text-center hidden">
    <button id="search-submit" type="submit" class="btn btn-flat col-12 col-lg-6 mx-auto">Search</button>
  </div>
</form>

app/views/trips/_infowindow.html.erb
<%= link_to trip_path(trip) do %>
<div class="map-infowindow m-0 h-100">
  <div class="row d-flex justify-content-between m-3">
    <h4 class="card-price m-0">
      ¥<%= trip.price %>
    </h4>
    <% if current_user == trip.driver %>
    <i class="fas fa-car fa-2x driver-icon"></i>
    <% else %>
    <%= cl_image_tag trip.driver.photo, gravity: "faces", crop: "fill", class: "avatar" %>
    <% end %>
  </div>
  <div class="row card-journey-destination m-3">
    <!-- <i class="fas fa-arrow-circle-right text-center"></i> --><h3><%= trip.end_point %></h3>
  </div>
</div>
<% end %>

app/views/trips/_map.html.erb
<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/trips/_new_banner.html.erb
<div class="banner position-relative d-flex align-items-center py-5 p-sm-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "banners/driver.jpg" %>);">
  <div class="container d-flex align-content-center justify-content-center flex-column h-100">
  </div>
</div>

app/views/trips/index.html.erb
<div id="trips-index" class="100vh-container">
  <% compact = params[:to].present? && params[:from].present? %>
  <%= render partial: "search_banner", locals: { banner_url: "banners/search.jpg", compact: compact } %>

  <div class="map-and-cards-container">
    <div class="row justify-content-center">

      <div id='trips-list' class="col-12 col-md-6 col-lg-5">

        <!-- <div class="text-center m-3">
          <p class="m-0">Driving to <%#= params[:to] %>?</p>
          <%#= link_to new_trip_path, class: "btn btn-outline-primary rounded mb-3" do %>
          <i class="fas fa-plus-circle"></i> Add your trip to TORIPPU
          <%# end %>
        </div> -->

        <% if @trips.empty? %>
          <p class="font-italic text-center">No trips available for your selection. <%= link_to "List your trip", new_trip_path %> or see the suggestions below.</p>
          <%= render partial: "trips/cards", locals: { trips: Trip.all.order(:start_time) } %>
        <% else %>
          <%= render partial: "trips/cards", locals: { trips: @trips } %>
        <% end %>
      </div>

      <div
        id="map-search" class="col-12 col-md-6 col-lg-7"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>

    </div>
  </div>
</div>

app/views/trips/new.html.erb
<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.0.0/mapbox-gl-directions.js'></script>
<link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.0.0/mapbox-gl-directions.css' type='text/css' />
<%= render partial: "shared/banner_category", locals: { title: "Create a new trip", banner_url: 'banners/driver.jpg' } %>

<div class="row justify-content-center position-relative">
  <div id="form-new-trip" class="col-12 col-lg-8 col-xl-6 p-3 pb-5">
    <div class="justify-content-center">
      <%= simple_form_for @trip do |f| %>
      <div class="form-groups-container row d-flex align-content-between">

        <div class="journey col-12 shadow" data-controller="mapbox">
          <div class="input-group my-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">From</span>
            </div>
            <%= f.input :start_point, label: false, placeholder: 'The pick-up address for other passengers', wrapper_html: { class: "m-0 flex-grow-1" }, input_html: { data: { target: "mapbox.from", action2: "change->mapbox#addFromMarker" } } %>
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">To</span>
            </div>
            <%= f.input :end_point, label: false, placeholder: 'Your destination address or city', wrapper_html: { class: "m-0 flex-grow-1" }, input_html: { data: {  target: "mapbox.to", action2: "change->mapbox#addToMarker" } } %>
          </div>
        </div>

        <div class="more-info col-12 shadow">
          <div id="trip-duration-info"></div>
          <div class="form-group row">
            <div class="input-group mb-3 col-6">
              <%= f.input :start_time, label: "Departure", wrapper_html: { class: "m-0 flex-grow-1 text-center datepicker" }, input_html: { class: "datepicker" } %>
            </div>
            <div class="input-group mb-3 col-6">
              <%= f.input :end_time, label: "Arrival (est.)", wrapper_html: { class: "m-0 flex-grow-1 text-center datepicker" }, input_html: { class: "datepicker" } %>
            </div>
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Description</span>
            </div>
            <%= f.input :description, as: :text, label: false, placeholder: 'Give more information about your travel, what kind of music you like, etc.', wrapper_html: { class: "m-0 flex-grow-1" } %>
          </div>
          <div class="form-group row">
            <div class="input-group mb-3 col-6">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Seats available</span>
              </div>
              <%= f.input :seats_available, label: false, collection: 1..8, wrapper_html: { class: "m-0 flex-grow-1" } %>
            </div>
            <div class="input-group mb-3 col-6">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">¥</span>
              </div>
              <%= f.input :price, label: false, placeholder: "price per seat", input_html: { min: '0', step: '100' } ,wrapper_html: { class: "m-0 flex-grow-1"} %>
            </div>
          </div>
          <%= f.submit "Let's ride!", class: 'btn btn-primary w-100'  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="map-create-trip" data-controller="mapbox" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" data-marker-from='[139.77,35.68]' data-marker-to='[135.4920315,34.69]'>

</div>

app/views/trips/show.html.erb
<%= render partial: "shared/banner_category", locals: { title: "Trip summary", banner_url: 'https://source.unsplash.com/collection/4894155/1600x900' } %>

<div class="tripshow-content container pb-5">
  <%= render partial: "trips/card_journey_summary", locals: { trip: @trip } %>

  <% if current_user ==  @trip.driver %>
    <div>
      <h2 class="text-center">Bookings for the trip: </h2>
    </div>
    <% @bookings.each do |booking| %>
      <%= render partial: "trips/card_bookings_driver", locals: { booking: booking } %>
    <% end %>
  <% else %>

    <div class="row w-100">

      <div class="col-12 col-md-6 col-lg-8">
        <%= render partial: "trips/details", locals: { trip: @trip } %>
      </div>

      <div class="col-12 col-md-6 col-lg-4">



          <% if @trip.booking?(current_user) && @trip.end_time > Time.now %>
            <%= render partial: "bookings/card_status", locals: { booking: @bookings.where(passenger: current_user).first } %>
          <% elsif  @trip.approved_passenger?(current_user) && @trip.end_time < Time.now %>
            <%= link_to new_trip_review_path(@trip), class: "btn btn-primary w-100 rounded mb-3 ml-4" do %>
                <i class="fas fa-plus-circle"></i> Add a review
              <% end %>
          <% else %>
            <%= render partial: "bookings/cart", locals: { trip: @trip, booking: @booking } %>
          <% end %>

      </div>
    </div>
  <% end %>
</div>