config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :trips, only: [:index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [:create, :update]
    resources :reviews, only: [:new, :create]
  end
  namespace :user do
    resources :trips, only: :index
  end
  resources :bookings, only: :destroy
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :passenger, class_name: "User"
  belongs_to :trip

  def validate(booking)
    if booking.seats_number < 1 ||
       booking.seats_number > trip.seats_remain ||
       booking.seats_number > trip.seats_available
      booking.errors[:seats_number] << 'shoupd be between 1 and seats_available'
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:update, :destroy]

  def create
    @trip = Trip.find(params[:trip_id])
    @booking = Booking.new(booking_params)
    @booking.passenger = current_user
    @booking.trip = @trip
    authorize @booking
    if @booking.save
      redirect_to trip_path(@trip)
    else
      render "trips/show"
    end
  end

  def update
    @trip = Trip.find(params[:trip_id])
    @booking.update(booking_params)
    redirect_to trip_path(@trip)
  end

  def destroy
    @booking.delete
    redirect_to trip_path(@booking.trip)
  end

  private

  def booking_params
    params.require(:booking).permit(:seats_number, :approved)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/views/bookings/_card_grid_2.html.erb
<div class="card-grid-2">
  <div class="card-grid-left">
    <h5><%=  element_1%></h5>
  </div>
  <div class="card-grid-right">
    <h5><%=  element_2%></h5>
  </div>
</div>

app/views/bookings/_card_status.html.erb
<div class="booking-cart border<%= booking.approved ? ' confirmed' : ' pending' %>">
  <div class="row">
    <div class="mx-5 w-100">
    <h4 class="text-center py-3 border-bottom">Request pending</h4>
      <div class="">
       <% if booking.approved?%>
         <p class="p-l-3"> You are <span class="confirmed">confirmed</span> for this trip!</p>
       <% else %>
         <p class="p-l-3"><%= @trip.driver.username %> hasn't approved your request yet...</p>
       <% end %>
     </div>
    </div>
  </div>
  <div class="row">
    <div class="mx-5 py-3 w-100">
      <div class="card-grid-2">
        <p>Number of requested seats: <%= booking.seats_number %></p>
      </div>

    </div>
  </div>
  <div class="row">
    <div class="mx-5 py-3 w-100">
      <% if policy(booking).destroy? %>
        <div>
        <%= link_to 'Cancel request', booking_path(booking),
                              method: :delete,
                              class:"btn btn-outline-danger w-100"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/_cart.html.erb
<div class="booking-cart border">
  <div class="row">
    <div class="mx-5 py-3 border-bottom w-100">
      <h3 class="m-0">¥<%= trip.price %> <span>per seat</span> </h3>
    </div>
  </div>
  <div class="row">
    <div class="mx-5 py-3 w-100">
      <h3> <%= pluralize trip.seats_remain, "seat"%> <span> remaining</span></h3>
      <%= simple_form_for [booking.trip, booking] do |f| %>
          <%= f.input :seats_number, label: "Number of seats", input_html: { min: 1, max: trip.seats_remain } %>
          <%= f.submit "Make a booking request", class: "btn btn-primary w-100" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/_cart_status.html.erb
_cart_status.html.erb