config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :trips, only: [:index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [:create, :update]
    resources :reviews, only: [:new, :create]
  end
  namespace :user do
    resources :trips, only: :index
  end
  resources :bookings, only: :destroy
end

app/views/shared/_banner_category.html.erb
<div class="banner position-relative d-flex align-items-center py-5 p-sm-3" data-target="navbar.banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path banner_url %>);">

  <div class="container d-flex justify-content-center flex-column h-100">
    <div>
      <h1 class="my-3 col-12 col-sm-12 p-0"><%= title %></h1>
    </form>
    </div>
  </div>


</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
   <i class="far fa-copyright"></i>2019, TORIPPU
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-torippu fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%#= image_tag "logo.jpg" %>
    <div class="logo d-flex align-items-center">
      <i class="fas fa-car mr-2"></i>
      <div class="logo-text">
        <p>TORIPPU</p>
        <p>トリップ</p>
      </div>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to new_trip_path, class: "btn btn-outline-light mr-3" do %>
            <i class="fas fa-plus-circle"></i> List a new trip
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", "#", class: "dropdown-item" %>
            <%= link_to "My trips", user_trips_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-outline-light" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_stars.html.erb
<% if  user.rating.nil? %>
  <p class="reviews-stars">No reviews yet...</p>
<% else %>
  <p class="reviews-stars">
  <%user.rating.times do%>
    <i class="fas fa-star"></i>
  <% end %>
  <%(5 - user.rating).times do%>
    <i class="far fa-star"></i>
  <% end %>
  (<%= user.rating%>)
  </p>
<% end%>